name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  schedule:
    # автооновлення з таблиці двічі на добу (00:00 і 12:00 UTC) — підлаштуй за потреби
    - cron: '0 */12 * * *'
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build site
        env:
          SHEET_CSV_URL: ${{ secrets.https://docs.google.com/spreadsheets/d/e/2PACX-1vSJfm-lwthFUkv7Y_mY46SnJetYdoLM7NrutbNatFOtXtA2tD3-HjoaskgSyM1Pnw/pub?gid=417554514&single=true&output=csv }}
          SITE_URL: https://starokostiantyniv.com
        run: node build.js

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
